:fn-ninjas: footnote:[https://ninjas.cl]

= Antora Docs Bootstrap

This is a simple configuration for creating documentation with https://docs.antora.org/[Antora Docs].

It includes:

- Dockerfile
- Kroki (Plant UML and others)
- Search

== Usage

A _Makefile_ and a _Taskfile.yml_ can be used to build the docs.
These are the same so you can choose which is best for your use case.

*Makefile*

- `make install`: Builds the Dockerfile.
- `make build`: Compiles Antora Docs.
- `make sh`: Opens the Container.
- `make server`: Starts a new server for the html version. (requires python3).

*Taskfile.yml*

- `task install`: Builds the Dockerfile.
- `task build`: Compiles Antora Docs.
- `task sh`: Opens the Container.
- `task server`: Starts a new server for the html version. (requires python3).

== Directories

- `antora/`: Contains the main antora docs configuration files and documentation.
- `docs/`: The build command will generate a docs directory so it can be used in Github pages.

This separation is important so the developer can use this template and add it 
to a ongoing project easily or start a new one using the file structure as a base.
The important thing is storing `antora-playbook.yml`` at the same level as the `.git` directory.

== License

Created with ❤️ by https://ninjas.cl[Camilo Castro] and https://github.com/NinjasCL/antora-docs-bootstrap/graphs/contributors[contributors]footnote:[https://github.com/NinjasCL/antora-docs-bootstrap/graphs/contributors]. for https://ninjas.cl[Ninjas.cl]{fn-ninjas}.

This document is licensed with http://creativecommons.org/licenses/by-nc-sa/4.0/[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International]footnote:[http://creativecommons.org/licenses/by-nc-sa/4.0/]

http://creativecommons.org/licenses/by-nc-sa/4.0/[image:https://raw.githubusercontent.com/NinjasCL/asciidoc-book-template/main/resources/images/by-nc-sa.svg[Creative Commons]]

Source code licensed with https://opensource.org/licenses/BSD-2-Clause[BSD-2]footnote:[https://opensource.org/licenses/BSD-2-Clause].

== 🤩 Credits

++++
<p>
  Made with <i class="fa fa-heart">&#9829;</i> by
  <a href="https://ninjas.cl">
    Ninjas.cl
  </a>.
</p>
++++


- Original Template: https://github.com/NinjasCL/asciidoc-book-template/tree/main[Asciidoc Book Template]
